### ISSUE TITLE
check behavior inside GitHub Action

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/is-fork-pr#122]
See if we detect forked PR for GitHub Action

**Comment by bahmutov** [comment]
Other repos are using the following condition to detect forked PR
```
# forked workflow (no acceess to build secrets)
  e2e-no-cypress-record:
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
```
